### ISSUE TITLE
Failing ingestions due to IOException

### ISSUE THREAD

**Issue by jrdh** [gbif/portal-feedback#1358]
Ingestion of our DwC-A dump has [failed the last two times](https://management-tools.gbif.org/crawl-history?uuid=7e380070-f762-11e1-a439-00145eb45e9a) and according to the [logs](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-3d,mode:quick,to:now-2d))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWDqIeCpf8lu3pmEHglJ,key:datasetKey,negate:!f,type:phrase,value:'7e380070-f762-11e1-a439-00145eb45e9a'),query:(match:(datasetKey:(query:'7e380070-f762-11e1-a439-00145eb45e9a',type:phrase))))),index:AWDqIeCpf8lu3pmEHglJ,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))) this is because of an error when reading the occurrence CSV:

```java
java.io.IOException: java.lang.IllegalStateException: java.text.ParseException: Unexpected character ('f' (code 102)): Expected separator ('"' (code 34)) or end-of-line at [Source: (BufferedReader); line: 424, column: 175]
    at org.gbif.crawler.dwca.validator.DwcaValidator.validateOccurrenceCore(DwcaValidator.java:177)
    at org.gbif.crawler.dwca.validator.DwcaValidator.check(DwcaValidator.java:107)
    at org.gbif.crawler.dwca.validator.DwcaValidator.validate(DwcaValidator.java:83)
    at org.gbif.crawler.dwca.validator.ValidatorService$DwcaDownloadFinishedMessageCallback.prepareAndRunValidation(ValidatorService.java:147)
    at org.gbif.crawler.dwca.validator.ValidatorService$DwcaDownloadFinishedMessageCallback.handleMessage(ValidatorService.java:100)
    at org.gbif.crawler.dwca.validator.ValidatorService$DwcaDownloadFinishedMessageCallback.handleMessage(ValidatorService.java:64)
    at org.gbif.common.messaging.MessageConsumer.handleCallback(MessageConsumer.java:101)
    at org.gbif.common.messaging.MessageConsumer.handleDelivery(MessageConsumer.java:65)
    at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
    at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: java.text.ParseException: Unexpected character ('f' (code 102)): Expected separator ('"' (code 34)) or end-of-line
 at [Source: (BufferedReader); line: 424, column: 175]
    at org.gbif.dwc.DwcRecordIterator.hasNext(DwcRecordIterator.java:70)
    at org.gbif.crawler.dwca.validator.DwcaValidator.validateOccurrenceCore(DwcaValidator.java:170)
    ... 12 common frames omitted
Caused by: java.text.ParseException: Unexpected character ('f' (code 102)): Expected separator ('"' (code 34)) or end-of-line
 at [Source: (BufferedReader); line: 424, column: 175]
    at org.gbif.utils.file.tabular.JacksonCsvFileReader.read(JacksonCsvFileReader.java:103)
    at org.gbif.utils.file.tabular.JacksonCsvFileReader.read(JacksonCsvFileReader.java:22)
    at org.gbif.dwc.DwcRecordIterator.hasNext(DwcRecordIterator.java:63)
    ... 13 common frames omitted
```

I believe this record is causing the issue: http://data.nhm.ac.uk/dataset/56e711e6-c847-4f99-915a-6894bb5c5dea/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/779, however, it hasn't changed since `2017-07-31` and already appears on GBIF (https://www.gbif.org/occurrence/1272133546) so it must have been ingested correctly at some point.

Looks like there's a bug somewhere and I think it's with the ingestor as the CSV looks valid (but complicated). We also haven't changed our DwC-A packaging software for a little while either.

**Comment by MattBlissett** [comment]
> valid (but complicated)

Indeed.

```
779,,"{""chronostratigraphy"": ""Cretaceous, Early Cretaceous, Albian - Late Cretaceous, Cenomanian"", ""cataloguedescription"": ""Very worn vertebra. Old catalogue says \""fragments of bone\""."", ""created"": ""2009-05-13"", ""barcode"": ""010039076"", ""project"": ""eMesozoic"", ""determinationnames"": ""Ornithocheirus"", ""subdepartment"": ""Vertebrates"", ""lithostratigraphy"": ""Selborne Group, Upper Greensand Formation, Cambridge Greensand Member"", ""imagecategory"": [""Register;Specimen""]}",,,Europe,Selborne Group,...[trimmed]...,,Cretaceous,,"Cambridge, Cambridge",England,Cambridge Greensand Member,,,,Reptilia,,Pterosauria
```

I recently changed the library used for CSV parsing, from a custom GBIF one to Jackson. I assume it's confused by the `\""` sequence, although `\` doesn't have any special meaning in CSV. Hopefully I can configure Jackson appropriately.

**Comment by jrdh** [comment]
Thanks @MattBlissett !
