### ISSUE TITLE
Empty data file that should have data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2272]
**Empty data file that should have data**

I have filtered a dataset to contain 1 million plus records.  However, unzipping the download reveals a csv file with no more than field labels?  See  `http://api.gbif.org/v1/occurrence/download/request/0032901-190918142434337.zip`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/03015651ab632287e4938f4dfb05840f:74d52c1084f7bedf8a158530899ea708b5753bf13b78da2cfb6b284e0368a22af92cd06e578cc2708930b5e80847392708b29f0771ca479567080f581d84f349)
System: Opera 63.0.3368 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=empty%20file
Window size: width 1880 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-31T01:59:19.688Z',mode:absolute,to:'2019-10-31T02:05:19.688Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-31T01:59:19.688Z',mode:absolute,to:'2019-10-31T02:05:19.688Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
https://www.gbif.org/occurrence/download/0032901-190918142434337

Rerunning the workflow hasn't helped.

`select count(*) from prod_h.occurrence_hdfs where (((contains("POLYGON ((-78.13477 -50.88867, -78.13477 49.13086, 105.0293 49.13086, 105.0293 -50.88867, -78.13477 -50.88867))", decimallatitude, decimallongitude) AND contains("MULTIPOLYGON (((180 46.534434784660405, 180 -50.791771264062575, 141.24023 -50.88867, 141.24023 -40.3418, 142.99805 -37.88086, 147.39258 -33.66211, 151.78711 -28.74023, 140.18555 -19.95117, 132.27539 -15.73242, 123.31055 -14.67773, 105.0293 -16.43555, 110.83008 17.49023, 148.79883 42.80273, 180 46.534434784660405)), ((-180 -50.791771264062575, -180 46.534434784660405, -158.29102 49.13086, -114.87305000000003 22.58789, -86.92383000000001 7.11914, -78.31054999999998 -11.33789, -78.13477 -50.53711, -180 -50.791771264062575)))", decimallatitude, decimallongitude))) AND (hascoordinate = true) AND ((taxonkey = 5014 OR kingdomkey = 5014 OR phylumkey = 5014 OR classkey = 5014 OR orderkey = 5014 OR familykey = 5014 OR genuskey = 5014 OR subgenuskey = 5014 OR specieskey = 5014)) AND (hasgeospatialissues = false));`

2192218

Hmmm.

**Comment by MattBlissett** [comment]
```
CREATE TABLE dl_debug ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
TBLPROPERTIES ("serialization.null.format"="")
AS SELECT
  gbifid, datasetkey, occurrenceid, kingdom, phylum, class, order_, family, genus, species, infraspecificepithet, taxonrank, scientificname, v_scientificname AS verbatimscientificname, v_scientificnameauthorship AS verbatimscientificnameauthorship, countrycode, locality,
  stateprovince, occurrencestatus, individualcount, publishingorgkey, decimallatitude, decimallongitude, coordinateuncertaintyinmeters, coordinateprecision, elevation, elevationaccuracy, depth, depthaccuracy, toISO8601(eventdate) AS eventdate, day, month, year, taxonkey,
  specieskey, basisofrecord, institutioncode, collectioncode, catalognumber, recordnumber, identifiedby, toISO8601(dateidentified) AS dateidentified, license, rightsholder, recordedby, typestatus, establishmentmeans, toISO8601(lastinterpreted) AS lastinterpreted,
  if(mediatype IS NULL,'',joinArray(mediatype,'\\;')) AS mediatype, if(issue IS NULL,'',joinArray(issue,'\\;')) AS issue
FROM prod_h.occurrence_hdfs WHERE
 (((contains("MULTIPOLYGON (((180 46.534434784660405, 180 -50.791771264062575, 141.24023 -50.88867, 141.24023 -40.3418, 142.99805 -37.88086, 147.39258 -33.66211, 151.78711 -28.74023, 140.18555 -19.95117, 132.27539 -15.73242, 123.31055 -14.67773, 105.0293 -16.43555, 110.83008 17.49023, 148.79883 42.80273, 180 46.534434784660405)), ((-180 -50.791771264062575, -180 46.534434784660405, -158.29102 49.13086, -114.87305000000003 22.58789, -86.92383000000001 7.11914, -78.31054999999998 -11.33789, -78.13477 -50.53711, -180 -50.791771264062575)))", decimallatitude, decimallongitude))) AND (hascoordinate = true) AND ((taxonkey = 5014 OR kingdomkey = 5014 OR phylumkey = 5014 OR classkey = 5014 OR orderkey = 5014 OR familykey = 5014 OR genuskey = 5014 OR subgenuskey = 5014 OR specieskey = 5014)) AND (hasgeospatialissues = false))
;
```

This query causes a fatal error: 

```
Error: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row {"gbifid":1055398956,"v_abstract":null,"v_accessrights":null,"v_accrualmethod":null,"v_accrualperiodicity":null,"v_accrualpolicy":null,"v_alternative":null,"v_audience":null,"v_available":null,"v_bibliographiccitation":null,"v_conformsto":null,"v_contributor":null,"v_coverage":null,"v_created":null,"v_creator":null,"v_date":null,"v_dateaccepted":null,"v_datecopyrighted":null,"v_datesubmitted":null,"v_description":null,"v_educationlevel":null,"v_extent":null,"v_format":null,"v_hasformat":null,"v_haspart":null,"v_hasversion":null,"v_identifier":null,"v_instructionalmethod":null,"v_isformatof":null,"v_ispartof":null,"v_isreferencedby":null,"v_isreplacedby":null,"v_isrequiredby":null,"v_isversionof":null,"v_issued":null,"v_language":null,"v_license":null,"v_mediator":null,"v_medium":null,"v_modified":null,"v_provenance":null,"v_publisher":null,"v_references":null,"v_relation":null,"v_replaces":null,"v_requires":null,"v_rights":null,"v_rightsholder":null,"v_source":null,"v_spatial":null,"v_subject":null,"v_tableofcontents":null,"v_temporal":null,"v_title":null,"v_type":null,"v_valid":null,"v_institutionid":null,"v_collectionid":null,"v_datasetid":null,"v_institutioncode":null,"v_collectioncode":null,"v_datasetname":null,"v_ownerinstitutioncode":null,"v_basisofrecord":null,"v_informationwithheld":null,"v_datageneralizations":null,"v_dynamicproperties":null,"v_occurrenceid":null,"v_catalognumber":null,"v_recordnumber":null,"v_recordedby":null,"v_individualcount":null,"v_organismquantity":null,"v_organismquantitytype":null,"v_sex":null,"v_lifestage":null,"v_reproductivecondition":null,"v_behavior":null,"v_establishmentmeans":null,"v_occurrencestatus":null,"v_preparations":null,"v_disposition":null,"v_associatedmedia":null,"v_associatedreferences":null,"v_associatedsequences":null,"v_associatedtaxa":null,"v_othercatalognumbers":null,"v_occurrenceremarks":null,"v_organismid":null,"v_organismname":null,"v_organismscope":null,"v_associatedoccurrences":null,"v_associatedorganisms":null,"v_previousidentifications":null,"v_organismremarks":null,"v_materialsampleid":null,"v_eventid":null,"v_parenteventid":null,"v_fieldnumber":null,"v_eventdate":null,"v_eventtime":null,"v_startdayofyear":null,"v_enddayofyear":null,"v_year":null,"v_month":null,"v_day":null,"v_verbatimeventdate":null,"v_habitat":null,"v_samplingprotocol":null,"v_samplingeffort":null,"v_samplesizevalue":null,"v_samplesizeunit":null,"v_fieldnotes":null,"v_eventremarks":null,"v_locationid":null,"v_highergeographyid":null,"v_highergeography":null,"v_continent":null,"v_waterbody":null,"v_islandgroup":null,"v_island":null,"v_country":null,"v_countrycode":null,"v_stateprovince":null,"v_county":null,"v_municipality":null,"v_locality":null,"v_verbatimlocality":null,"v_minimumelevationinmeters":null,"v_maximumelevationinmeters":null,"v_verbatimelevation":null,"v_minimumdepthinmeters":null,"v_maximumdepthinmeters":null,"v_verbatimdepth":null,"v_minimumdistanceabovesurfaceinmeters":null,"v_maximumdistanceabovesurfaceinmeters":null,"v_locationaccordingto":null,"v_locationremarks":null,"v_decimallatitude":null,"v_decimallongitude":null,"v_geodeticdatum":null,"v_coordinateuncertaintyinmeters":null,"v_coordinateprecision":null,"v_pointradiusspatialfit":null,"v_verbatimcoordinates":null,"v_verbatimlatitude":null,"v_verbatimlongitude":null,"v_verbatimcoordinatesystem":null,"v_verbatimsrs":null,"v_footprintwkt":null,"v_footprintsrs":null,"v_footprintspatialfit":null,"v_georeferencedby":null,"v_georeferenceddate":null,"v_georeferenceprotocol":null,"v_georeferencesources":null,"v_georeferenceverificationstatus":null,"v_georeferenceremarks":null,"v_geologicalcontextid":null,"v_earliesteonorlowesteonothem":null,"v_latesteonorhighesteonothem":null,"v_earliesteraorlowesterathem":null,"v_latesteraorhighesterathem":null,"v_earliestperiodorlowestsystem":null,"v_latestperiodorhighestsystem":null,"v_earliestepochorlowestseries":null,"v_latestepochorhighestseries":null,"v_earliestageorloweststage":null,"v_latestageorhigheststage":null,"v_lowestbiostratigraphiczone":null,"v_highestbiostratigraphiczone":null,"v_lithostratigraphicterms":null,"v_group":null,"v_formation":null,"v_member":null,"v_bed":null,"v_identificationid":null,"v_identificationqualifier":null,"v_typestatus":null,"v_identifiedby":null,"v_dateidentified":null,"v_identificationreferences":null,"v_identificationverificationstatus":null,"v_identificationremarks":null,"v_taxonid":null,"v_scientificnameid":null,"v_acceptednameusageid":null,"v_parentnameusageid":null,"v_originalnameusageid":null,"v_nameaccordingtoid":null,"v_namepublishedinid":null,"v_taxonconceptid":null,"v_scientificname":"Eugenia plumea Ridl.","v_acceptednameusage":null,"v_parentnameusage":null,"v_originalnameusage":null,"v_nameaccordingto":null,"v_namepublishedin":null,"v_namepublishedinyear":null,"v_higherclassification":null,"v_kingdom":null,"v_phylum":null,"v_class":null,"v_order":null,"v_family":null,"v_genus":null,"v_subgenus":null,"v_specificepithet":null,"v_infraspecificepithet":null,"v_taxonrank":null,"v_verbatimtaxonrank":null,"v_scientificnameauthorship":"Ridl.","v_vernacularname":null,"v_nomenclaturalcode":null,"v_taxonomicstatus":null,"v_nomenclaturalstatus":null,"v_taxonremarks":null,"identifiercount":null,"crawlid":null,"fragmentcreated":null,"xmlschema":null,"publishingorgkey":"19456090-b49a-11d8-abeb-b8a03c50a862","unitqualifier":null,"networkkey":null,"installationkey":null,"abstract":null,"accessrights":null,"accrualmethod":null,"accrualperiodicity":null,"accrualpolicy":null,"alternative":null,"audience":null,"available":null,"bibliographiccitation":null,"conformsto":null,"contributor":null,"coverage":null,"created":null,"creator":null,"date_":null,"dateaccepted":null,"datecopyrighted":null,"datesubmitted":null,"description":null,"educationlevel":null,"extent":null,"format_":null,"hasformat":null,"haspart":null,"hasversion":null,"identifier":null,"instructionalmethod":null,"isformatof":null,"ispartof":null,"isreferencedby":null,"isreplacedby":null,"isrequiredby":null,"isversionof":null,"issued":null,"language":null,"license":"CC0_1_0","mediator":null,"medium":null,"modified":null,"provenance":null,"publisher":null,"references":null,"relation":null,"replaces":null,"requires":null,"rights":null,"rightsholder":null,"source":null,"spatial":null,"subject":null,"tableofcontents":null,"temporal":null,"title":null,"type":null,"valid":null,"institutionid":null,"collectionid":null,"datasetid":null,"institutioncode":"NHMUK","collectioncode":"BOT","datasetname":null,"ownerinstitutioncode":null,"basisofrecord":"PRESERVED_SPECIMEN","informationwithheld":null,"datageneralizations":null,"dynamicproperties":null,"occurrenceid":"33e8ab9b-cd1d-4e18-8864-9859d2b4c662","catalognumber":"BM000944234","recordnumber":"s.n.","recordedby":"Cecil Boden Kloss","individualcount":null,"organismquantity":null,"organismquantitytype":null,"sex":null,"lifestage":null,"reproductivecondition":null,"behavior":null,"establishmentmeans":null,"occurrencestatus":null,"preparations":null,"disposition":null,"associatedreferences":null,"associatedsequences":null,"associatedtaxa":null,"othercatalognumbers":null,"occurrenceremarks":null,"organismid":null,"organismname":null,"organismscope":null,"associatedoccurrences":null,"associatedorganisms":null,"previousidentifications":null,"organismremarks":null,"materialsampleid":null,"eventid":null,"parenteventid":null,"fieldnumber":null,"eventdate":null,"eventtime":null,"startdayofyear":null,"enddayofyear":null,"year":null,"month":null,"day":null,"verbatimeventdate":null,"habitat":null,"samplingprotocol":null,"samplingeffort":null,"samplesizevalue":null,"samplesizeunit":null,"fieldnotes":null,"eventremarks":null,"locationid":null,"highergeographyid":null,"highergeography":null,"continent":null,"waterbody":null,"islandgroup":null,"island":null,"countrycode":"ID","stateprovince":null,"county":null,"municipality":null,"locality":null,"verbatimlocality":null,"verbatimelevation":null,"verbatimdepth":null,"minimumdistanceabovesurfaceinmeters":null,"maximumdistanceabovesurfaceinmeters":null,"locationaccordingto":null,"locationremarks":null,"decimallatitude":-3.45,"decimallongitude":136.97,"coordinateuncertaintyinmeters":null,"coordinateprecision":null,"pointradiusspatialfit":null,"verbatimcoordinatesystem":null,"verbatimsrs":null,"footprintwkt":null,"footprintsrs":null,"footprintspatialfit":null,"georeferencedby":null,"georeferenceddate":null,"georeferenceprotocol":null,"georeferencesources":null,"georeferenceverificationstatus":null,"georeferenceremarks":null,"geologicalcontextid":null,"earliesteonorlowesteonothem":null,"latesteonorhighesteonothem":null,"earliesteraorlowesterathem":null,"latesteraorhighesterathem":null,"earliestperiodorlowestsystem":null,"latestperiodorhighestsystem":null,"earliestepochorlowestseries":null,"latestepochorhighestseries":null,"earliestageorloweststage":null,"latestageorhigheststage":null,"lowestbiostratigraphiczone":null,"highestbiostratigraphiczone":null,"lithostratigraphicterms":null,"group_":null,"formation":null,"member":null,"bed":null,"identificationid":null,"identificationqualifier":null,"typestatus":"TYPE","identifiedby":null,"dateidentified":null,"identificationreferences":null,"identificationverificationstatus":null,"identificationremarks":null,"taxonid":null,"scientificnameid":null,"acceptednameusageid":null,"parentnameusageid":null,"originalnameusageid":null,"nameaccordingtoid":null,"namepublishedinid":null,"taxonconceptid":null,"scientificname":"Eugenia plumea Ridl.","acceptednameusage":null,"parentnameusage":null,"originalnameusage":null,"nameaccordingto":null,"namepublishedin":null,"namepublishedinyear":null,"higherclassification":null,"kingdom":"Plantae","phylum":"Tracheophyta","class":"Magnoliopsida","order_":"Myrtales","family":"Myrtaceae","genus":"Syzygium","subgenus":null,"specificepithet":null,"infraspecificepithet":null,"taxonrank":"SPECIES","verbatimtaxonrank":null,"vernacularname":null,"nomenclaturalcode":null,"taxonomicstatus":null,"nomenclaturalstatus":null,"taxonremarks":null,"datasetkey":"7e380070-f762-11e1-a439-00145eb45e9a","publishingcountry":null,"lastinterpreted":1569011060159,"elevation":null,"elevationaccuracy":null,"depth":null,"depthaccuracy":null,"distanceabovesurface":null,"distanceabovesurfaceaccuracy":null,"issue":["GEODETIC_DATUM_ASSUMED_WGS84","RECORDED_DATE_INVALID"],"hascoordinate":true,"hasgeospatialissues":false,"taxonkey":5418810,"acceptedtaxonkey":null,"kingdomkey":6,"phylumkey":7707728,"classkey":220,"orderkey":690,"familykey":5014,"genuskey":3029010,"subgenuskey":null,"specieskey":3182522,"species":"Syzygium plumeum","genericname":null,"acceptedscientificname":null,"typifiedname":null,"protocol":null,"lastparsed":null,"lastcrawled":null,"repatriated":null,"mediatype":["STILLIMAGE"],"ext_multimedia":null}
        at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:179)
        at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:459)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

**Comment by MattBlissett** [comment]
Fixed in https://github.com/gbif/occurrence/commit/60b7d2420f353ba9b3ffaa66e029fe2a1bf30f66, user also emailed so will inform them that way.
